[phases.setup]
nixPkgs = ["python311", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements-railway.txt"
]

[start]
cmd = "python -m src.main"